# pull the base image
FROM node:alpine

# set the working direction
#WORKDIR /client

# add `/app/node_modules/.bin` to $PATH
ENV PATH /client/node_modules/.bin:$PATH

# install app dependencies
COPY ./client/package*.json ./

#COPY package-lock.json ./

RUN npm install

# add app
COPY . ./

# start app
CMD ["npm", "start", "--prefix", "client"]